export const META = {
  title: 'Saeyoung Choi | Product Planner',
  siteName: 'Saeyoung Choi | Product Planner',
  description: 'A Product Planner bridging design & development',
  keyword: [
    '최세영',
    'saeyoung choi',
    'frontend developer',
    'frontend engineer',
    'product manager',
    'product planner',
    'product designer',
    'product engineer',
    'ui/ux designer',
    'ui/ux engineer',
    'ui developer',
    'ui engineer',
  ],
  url: 'https://www.saeyoung-choi.site',
  ogImage: '/images/opengraph-image.png',
  favicon: '/images/favicon.ico',
} as const;
